version: '3.9'

services:
  db:
    container_name: db
    image: postgres:14.2
    restart: "no"
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
      TZ: "Europe/Brussels"
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
      - ./datetime/timezone:/etc/timezone
      - ./datetime/localtime:/etc/localtime
    networks:
      - heating

  phoenix:
    container_name: phoenix
    image: home_automation/phoenix
    build: 
      context: ./home_automation/
    environment:
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: home_automation_dev
      PGPORT: 5432
      # Hostname of our Postgres container.
      PGHOST: db
      MIX_ENV: dev
      PLUG_URL: "${PLUG_URL:-http://plug:5000}"
      TEMP_URL: "${TEMP_URL:-http://bathroomtemp/temp}"
      TEMP_POLLING_TIME: 60000
    ports:
      - '80:4000'
    depends_on:
      - db
    extra_hosts:
      - "bathroomtemp:192.168.0.230"
    volumes:
      - ./home_automation:/app
      - ./datetime/timezone:/etc/timezone
      - ./datetime/localtime:/etc/localtime
    networks:
      - heating

  plug_communication:
    container_name: plug
    image: home_automation/plug_communication
    build:
      context: plug_communication
    environment:
      PLUG_IP: "192.168.0.159"
    ports:
      - '5000:5000'
    networks:
      - heating
    extra_hosts:
      - "smartplug:192.168.0.159"

  plug_mock:
    container_name: plug_mock
    image: home_automation/plug_mock
    build:
      context: mock/plug
    ports:
      - '5001:5000'
    networks:
      - heating

  temp_mock:
    container_name: temp_mock
    image: home_automation/temp_mock
    build:
      context: mock/temp_sensor
    ports:
      - '5002:5000'
    networks:
      - heating


volumes:
  pgdata:

networks:
  heating:
    driver: bridge
    ipam:
      driver: default